##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.external.kafka_connect:5.4.0 AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT "/etc/confluent/docker/run"
COPY ./conteco/configs/etc/confluent/docker/healthcheck.sh /etc/confluent/docker/healthcheck.sh
RUN chmod 777 /etc/confluent/docker/healthcheck.sh
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="kafka_connect" \
    CONTECO_NAME="tocloud" \
    CONTECO_TAG="5.4.0" \
    CONTECO_BASE="external.kafka_connect:5.4.0" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="kafka_connect" \
      io.vcweb.name="tocloud" \
      io.vcweb.tag="5.4.0" \
      io.vcweb.base="external.kafka_connect:5.4.0" \
      io.vcweb.build="image-base" \
      io.vcweb.label="kafka_connect.tocloud - ContEco" \
      io.vcweb.description="Confluent Kafka Connect to cloud image, with configuration changes." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.kafka_connect.tocloud --help"
##### END image.base/Dockerfile/env-labels-footer #####
