##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="kafka_connect" \
    CONTECO_NAME="sasl" \
    CONTECO_TAG="6.0.0" \
    CONTECO_BASE="controlplane.base" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="kafka_connect" \
      io.vcweb.name="sasl" \
      io.vcweb.tag="6.0.0" \
      io.vcweb.base="controlplane.base" \
      io.vcweb.build="image-base" \
      io.vcweb.label="kafka_connect.sasl - ContEco" \
      io.vcweb.description="Confluent Kafka Connect image, with SASL authentication." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.kafka_connect.sasl --help"
##### END image.base/Dockerfile/env-labels-footer #####
