#!/usr/bin/env bash

export CONTECO_LABEL="kafka_connect.sasl - ContEco"
export CONTECO_DESCRIPTION="Confluent Kafka Connect image, with SASL authentication."

export CONTECO_TYPE="kafka_connect"
export CONTECO_NAME="sasl"
export CONTECO_TAG="6.0.0"

export CONTECO_BUILD="image-base"

export CONTECO_EXTERNAL_IMAGE_NAME="vcwebio/conteco.external.kafka_connect:6.0.0"
